import type { Metadata } from "next";
import { Suspense } from "react";
import PageHero from "@/components/PageHero";
import RFQForm from "@/components/RFQForm";
import { Mail, Message } from "@/components/Icons";
import { site, whatsappUrl } from "@/lib/site";

export const metadata: Metadata = { title: "Contact & RFQ", description: "Contact Aurchain Biotech for peptide pricing, specifications, custom synthesis, and B2B supply inquiries." };
export default function ContactPage(){return <><PageHero eyebrow="Contact & RFQ" title="Let’s make your next peptide project simpler." intro="Send us your product, sequence, specification, and quantity. We aim to respond to qualified B2B inquiries within one business day."/><section id="rfq" className="scroll-mt-24 py-20"><div className="shell grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow">Talk with our team</p><h2 className="display mt-4 text-4xl">How can we help?</h2><p className="mt-5 text-sm leading-7 text-ink/60">Use the form for a structured quotation, or reach us directly for a quick product and availability conversation.</p><div className="mt-8 space-y-3"><a href={`mailto:${site.email}`} className="flex items-center gap-4 rounded-2xl bg-fog p-5"><span className="grid h-11 w-11 place-items-center rounded-full bg-white"><Mail className="h-5 w-5 text-teal"/></span><span><span className="block text-[10px] font-bold uppercase tracking-[.16em] text-ink/40">Email</span><span className="mt-1 block text-sm font-bold">{site.email}</span></span></a><a href={whatsappUrl()} target="_blank" rel="noreferrer" className="flex items-center gap-4 rounded-2xl bg-fog p-5"><span className="grid h-11 w-11 place-items-center rounded-full bg-white"><Message className="h-5 w-5 text-teal"/></span><span><span className="block text-[10px] font-bold uppercase tracking-[.16em] text-ink/40">WhatsApp</span><span className="mt-1 block text-sm font-bold">Message our sales team</span></span></a></div><p className="mt-8 text-xs leading-6 text-ink/40">{site.location}<br/>Business inquiries in English are welcome.</p></div><Suspense fallback={<div className="card">Loading inquiry form…</div>}><RFQForm/></Suspense></div></section></>}
