import Link from "next/link";
import { Arrow, Check } from "@/components/Icons";
import CTA from "@/components/CTA";

const capabilities = [
  ["01", "Research Peptides", "Consistent, traceable peptide supply for qualified laboratory and R&D applications.", "/products"],
  ["02", "Cosmetic Peptides", "Functional peptide ingredients for formulation development, scale-up, and brand programs.", "/products"],
  ["03", "Custom Synthesis", "Sequence-specific synthesis with flexible purity, modification, and analytical options.", "/custom-peptide-synthesis"],
  ["04", "Bulk & OEM/ODM", "Commercial quantities, tailored packaging, and supply support built around your program.", "/contact#rfq"]
];

export default function Home() {
  return <>
    <section className="relative min-h-[720px] overflow-hidden bg-fog">
      <div className="absolute inset-0 grid-lines"/><div className="absolute -right-40 -top-32 h-[620px] w-[620px] rounded-full border-[100px] border-mint/70"/>
      <div className="shell relative grid min-h-[720px] items-center gap-10 py-20 lg:grid-cols-[1.1fr_.9fr]">
        <div><p className="eyebrow">Peptide solutions for ambitious teams</p><h1 className="display mt-6 max-w-3xl text-[54px] text-ink sm:text-7xl lg:text-[82px]">Precision in every <span className="italic text-teal">sequence.</span></h1><p className="mt-7 max-w-xl text-base leading-8 text-ink/65 sm:text-lg">Research peptides, cosmetic actives, custom synthesis, and scalable B2B supply—supported by responsive service and documented quality.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/products" className="btn-primary">Explore Products <Arrow className="h-4 w-4"/></Link><Link href="/contact#rfq" className="btn-secondary">Start an RFQ</Link></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-xs font-bold text-ink/55">{["Batch-specific COA", "Flexible quantities", "Global B2B support"].map(x => <span key={x} className="flex items-center gap-2"><Check className="h-4 w-4 text-teal"/>{x}</span>)}</div></div>
        <div className="relative mx-auto hidden h-[470px] w-full max-w-[470px] lg:block"><div className="absolute inset-8 rounded-full border border-pine/15"/><div className="absolute inset-24 rounded-full border border-dashed border-teal/35"/><div className="molecule-float absolute left-[35%] top-[28%] h-36 w-36 rounded-full bg-pine shadow-[0_30px_80px_rgba(22,75,70,.3)]"><span className="absolute left-1/2 top-1/2 h-3 w-3 -translate-x-1/2 -translate-y-1/2 rounded-full bg-gold"/></div>{[[8,42],[72,16],[77,70],[15,78],[48,88]].map((v,i)=><span key={i} className="absolute h-7 w-7 rounded-full border-[6px] border-white bg-teal shadow-md" style={{left:`${v[0]}%`,top:`${v[1]}%`}}/>)}<div className="absolute bottom-8 right-0 rounded-2xl border border-ink/10 bg-white/90 p-5 shadow-soft backdrop-blur"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-teal">Quality framework</p><p className="mt-2 font-serif text-xl">Identity · Purity · Traceability</p></div></div>
      </div>
    </section>
    <section className="py-24"><div className="shell"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Built for B2B</p><h2 className="display mt-4 text-4xl sm:text-5xl">From early research to dependable supply.</h2><p className="mt-6 max-w-md text-sm leading-7 text-ink/60">A focused partner for peptide sourcing, development, and scale-up—without unnecessary complexity.</p></div><div className="grid gap-px overflow-hidden rounded-[24px] border border-ink/10 bg-ink/10 sm:grid-cols-2">{capabilities.map(([n,t,d,h]) => <Link href={h} key={t} className="group bg-white p-7 transition hover:bg-fog"><span className="text-[11px] font-bold text-teal">{n}</span><h3 className="mt-8 font-serif text-2xl">{t}</h3><p className="mt-3 text-sm leading-7 text-ink/55">{d}</p><Arrow className="mt-6 h-5 w-5 text-teal transition group-hover:translate-x-1"/></Link>)}</div></div></div></section>
    <section className="bg-fog py-24"><div className="shell grid gap-12 lg:grid-cols-2 lg:items-center"><div className="relative min-h-[420px] overflow-hidden rounded-[28px] bg-pine p-9 text-white grid-lines"><div className="absolute -bottom-24 -right-20 h-72 w-72 rounded-full border-[50px] border-white/5"/><p className="text-xs font-bold uppercase tracking-[.2em] text-gold">A clear process</p><div className="relative mt-14 space-y-6">{[["01","Define","Sequence, grade, quantity, timeline"],["02","Produce","Synthesis, purification, lyophilization"],["03","Verify","Analytical review and documentation"],["04","Deliver","Protective packing and coordinated shipping"]].map(([n,t,d])=><div key={n} className="grid grid-cols-[42px_1fr] gap-3 border-b border-white/10 pb-5"><span className="text-xs text-gold">{n}</span><div><p className="font-bold">{t}</p><p className="mt-1 text-xs text-white/50">{d}</p></div></div>)}</div></div><div><p className="eyebrow">Custom peptide synthesis</p><h2 className="display mt-4 text-4xl sm:text-5xl">Your target. Our disciplined workflow.</h2><p className="mt-6 text-base leading-8 text-ink/60">Whether you need milligram research material or a larger development batch, we align synthesis strategy and analytics with your intended application.</p><ul className="mt-7 grid gap-3 text-sm font-bold sm:grid-cols-2">{["Standard & modified peptides","Multiple purity options","HPLC & MS documentation","Flexible packaging","Scale-up support","Confidential project handling"].map(x=><li key={x} className="flex items-center gap-3"><span className="grid h-6 w-6 place-items-center rounded-full bg-mint"><Check className="h-3.5 w-3.5 text-teal"/></span>{x}</li>)}</ul><Link href="/custom-peptide-synthesis" className="btn-primary mt-9">View capabilities <Arrow className="h-4 w-4"/></Link></div></div></section>
    <CTA/>
  </>;
}
